package secureicon;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.PixelGrabber;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class Frame extends javax.swing.JFrame {

    Connection con;
    String url ="jdbc:derby://localhost:1527/";
    String dbName = "Wireless";
    String driver = "org.apache.derby.jdbc.ClientDriver";
    String userName = "wifi";
    String password = "wifi";
    File selectedFile = null;
    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        jPanel3.setVisible(false);
        //this.setIconImage(Toolkit.getDefaultToolkit().getImage("/Users/sukasidil/NetBeansProjects/SecureIcon/src/secureicon/unicorn-08.jpg"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SecurIcon");
        setBackground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(200, 200));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(177, 193, 220));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Password:");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 50, 90, 30);

        jTextField2.setEditable(false);
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickForText2(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(100, 50, 100, 30);

        jButton1.setText("Log in");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(60, 90, 90, 29);

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jButton2.setText("Sign up");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(100, 140, 50, 20);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("User Name:");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 90, 30);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(100, 10, 100, 30);

        jLabel4.setBackground(new java.awt.Color(177, 193, 220));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel4.setText("If you doens't have      ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 120, 110, 20);

        jLabel5.setBackground(new java.awt.Color(177, 193, 220));
        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel5.setText("an account, Please");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 140, 100, 13);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(130, 90, 210, 170);

        jPanel3.setBackground(new java.awt.Color(177, 193, 220));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setText("User Name:");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 10, 90, 30);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setText("Password:");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 50, 90, 30);
        jPanel3.add(jTextField3);
        jTextField3.setBounds(100, 10, 100, 30);

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(110, 110, 80, 29);

        jButton4.setText("Upload");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(110, 80, 80, 30);

        jTextField4.setEditable(false);
        jPanel3.add(jTextField4);
        jTextField4.setBounds(100, 50, 100, 30);

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(10, 110, 80, 29);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(250, 10, 220, 150);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secureicon/unicorn-08.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 480, 350);
        jLabel2.getAccessibleContext().setAccessibleName("jLabel2");

        jMenuBar1.setBackground(new java.awt.Color(228, 227, 234));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 2, new java.awt.Color(0, 0, 0)));

        jMenu1.setBackground(new java.awt.Color(226, 225, 233));
        jMenu1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenu1.setText("SecurIcon");

        jMenuItem3.setText("Start Connection");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setBackground(new java.awt.Color(226, 225, 233));
        jMenuItem2.setText("About SecurIcon");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setBackground(new java.awt.Color(226, 225, 233));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //about
        JOptionPane.showMessageDialog(this,"Created by Idil Sukas, Okan Gul, Nilay Altun","About",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //Exit
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Sign in
        try {
            Class.forName(driver).newInstance();
            con = DriverManager.getConnection(url+dbName,userName,password);
            Statement st = con.createStatement();
            
            String username=jTextField1.getText();
            String userNameQuery = "SELECT * FROM DATA "
                    + "WHERE USERNAME='" + username + "'";
            ResultSet rs = st.executeQuery(userNameQuery);           
            if (rs.next()){
                String text=jTextField2.getText();
                if (!text.trim().isEmpty()) {
                    File image = new File("/Users/sukasidil/NetBeansProjects/images/image2.jpg");
                    FileOutputStream fos = new FileOutputStream(image);

                    byte[] buffer = new byte[1];
                    InputStream is = rs.getBinaryStream(2);
                    while (is.read(buffer) > 0) {
                        fos.write(buffer);
                    }
                    fos.close();

                    String file1 = "/Users/sukasidil/NetBeansProjects/images/image.jpg";
                    String file2 = "/Users/sukasidil/NetBeansProjects/images/image2.jpg";

                    Image image1 = Toolkit.getDefaultToolkit().getImage(file1);
                    Image image2 = Toolkit.getDefaultToolkit().getImage(file2);

                    try {

                        PixelGrabber grab1 =new PixelGrabber(image1, 0, 0, -1, -1, false);
                        PixelGrabber grab2 =new PixelGrabber(image2, 0, 0, -1, -1, false);

                        int[] data1 = null;

                        if (grab1.grabPixels()) {
                            int width = grab1.getWidth();
                            int height = grab1.getHeight();
                            data1 = new int[width * height];
                            data1 = (int[]) grab1.getPixels();
                        }
                        int[] data2 = null;

                        if (grab2.grabPixels()) {
                            int width = grab2.getWidth();
                            int height = grab2.getHeight();
                            data2 = new int[width * height];
                            data2 = (int[]) grab2.getPixels();
                        }

                        if (java.util.Arrays.equals(data1, data2)) {
                            JOptionPane.showMessageDialog(this,"You logged in successfully!","SecurIcon",JOptionPane.PLAIN_MESSAGE);                        
                            jTextField1.setText("");
                            jTextField2.setText("");
                            jPanel2.setVisible(false);

                            new Frame2().setVisible(true);
                            Frame.this.setVisible(false);
                        }
                        else {
                            JOptionPane.showMessageDialog(this,"The username and password you entered don't match.","SecurIcon",JOptionPane.PLAIN_MESSAGE);
                            jTextField1.setText("");
                            jTextField2.setText("");

                        }
 
                    } catch (InterruptedException e1) {
                        e1.printStackTrace();
                    }
                }
                else {
                    JOptionPane.showMessageDialog(this,"You have to choose image!","SecurIcon",JOptionPane.PLAIN_MESSAGE);
                }
                
            } 
            else {
                JOptionPane.showMessageDialog(this,"Something is wrong, Please try again!","SecurIcon",JOptionPane.PLAIN_MESSAGE);
                jTextField1.setText("");
                jTextField2.setText("");
            }
            con.close();
            
        } catch (Exception e) {
            
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
  
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jPanel2.setVisible(false);
        jPanel3.setVisible(true);
        jPanel3.setLocation(130, 100);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //submit button
        try {
            
            Class.forName(driver).newInstance();
            con = DriverManager.getConnection(url+dbName,userName,password);
            
            String text1=jTextField3.getText();
            
            Statement st = con.createStatement();
            String query = "SELECT * FROM DATA "
                    + "WHERE USERNAME='" + text1 + "'";
            ResultSet rs = st.executeQuery(query);           
            if (rs.next()){
                JOptionPane.showMessageDialog(this,"Please, Try different username! ","Sign Up",JOptionPane.PLAIN_MESSAGE);
                jTextField3.setText("");
                selectedFile = null;
                jTextField4.setText("");
                con.close();
            } 
            
            else if (text1 != null && !text1.trim().isEmpty() && selectedFile != null) {
                
                String image = "INSERT INTO DATA (USERNAME,IMAGE) VALUES (?,?)";
                PreparedStatement ps = con.prepareStatement(image);
                InputStream is = new FileInputStream(selectedFile);
                ps.setBlob(2,is);
                ps.setString(1, text1);
                
                ps.executeUpdate();
                
                jPanel2.setVisible(true);
                jPanel3.setVisible(false);
                JOptionPane.showMessageDialog(this,"User was successfully created!","Sign Up",JOptionPane.PLAIN_MESSAGE);

                jTextField3.setText("");
                selectedFile = null;
                jTextField4.setText("");
                
                con.close();

             } 
            else {
                JOptionPane.showMessageDialog(this,"Please, Enter valid value!","Sign Up",JOptionPane.PLAIN_MESSAGE);
             }

        }catch (Exception e){
            System.out.println("There is no database connection!");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed
                
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //upload button
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            jTextField4.setText(path);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        //start connection
        try {
            
            int filesize=6022386; // filesize temporary hardcoded

            long start = System.currentTimeMillis();
            int bytesRead;
            int current = 0;
            ServerSocket servsock = new ServerSocket(8000);
            
            System.out.println("Waiting...");

            Socket sock = servsock.accept();
            System.out.println("Accepted connection : " + sock);

      // receive file
            byte [] mybytearray  = new byte [filesize];
            InputStream is = sock.getInputStream();
            FileOutputStream fos = new FileOutputStream("/Users/sukasidil/NetBeansProjects/images/image.jpg"); // destination path and name of file
            BufferedOutputStream bos = new BufferedOutputStream(fos);
            bytesRead = is.read(mybytearray,0,mybytearray.length);
            current = bytesRead;
            System.out.println("Accepted connection2 : " + sock);
            do {
                bytesRead =
                is.read(mybytearray, current, (mybytearray.length-current));
                if(bytesRead >= 0) current += bytesRead;
                
            } while(bytesRead > -1);

            bos.write(mybytearray, 0 , current);
            bos.flush();
            long end = System.currentTimeMillis();
            System.out.println(end-start);

            jTextField2.setText("******");
            jTextField2.setEditable(false);
            bos.close();

            sock.close();

        }catch (Exception e){
            System.out.println("Fail");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mouseClickForText2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickForText2

    }//GEN-LAST:event_mouseClickForText2

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //Back
        jTextField3.setText("");
        jPanel2.setVisible(true);
        jPanel3.setVisible(false);
        jPanel2.setLocation(130, 100);
        jTextField1.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
    */

    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
                
            }
        });
        
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
